openapi: 3.0.0
info:
  description: web market
  title: web market
  version: '1.0'
  contact:
    name: web-market
servers:
  - url: 'http://localhost:3000'
tags:
  - name: get
  - name: post
  - name: patch
  - name: delete
paths:
  '/users/{userId}':
    parameters:
      - schema:
          type: integer
        name: userId
        in: path
        required: true
        description: Id of an existing user.
    get:
      summary: Get User Info by User ID
      tags:
        - get
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples: {}
        '401':
          description: Unauthorized
          content:
            text/plain:
              schema:
                type: string
              examples:
                example-1:
                  value: Unauthorized
        '404':
          description: User Not Found
          content:
            text/plain:
              schema:
                type: string
              examples:
                example-1:
                  value: User Not Found
      operationId: get-users-userId
      description: Retrieve the information of the user with the matching user ID.
    patch:
      tags:
        - patch
      summary: Update User Information
      operationId: patch-users-userId
      responses:
        '200':
          description: User Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Updated User user1@gmail.com:
                  value:
                    _id: 1
                    email: user1@gmail.com
                    createDate: '2022-01-01'
                    contactInfo:
                      name: user1
                      email: user1@gmail.com
                      phone: '1234567'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
              examples:
                example-1:
                  value: Unauthorized
        '404':
          description: User Not Found
          content:
            text/plain:
              schema:
                type: string
              examples:
                example-1:
                  value: User Not Found
        '409':
          description: Email Already Taken
          content:
            text/plain:
              schema:
                type: string
              examples:
                example-1:
                  value: Email Already Taken
      description: Update the information of an existing user.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'If a new email is given, the user''s email verified property will be set to false.'
                password:
                  type: string
                contactInfo:
                  $ref: '#/components/schemas/Contact'
            examples:
              Update Email:
                value:
                  email: user2@gmail.com
              Update Password:
                value:
                  password: string
        description: Patch user properties to update.
  /user:
    post:
      tags:
        - post
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                New User user1@gmail.com:
                  value:
                    _id: 1
                    email: user1@gmail.com
                    createDate: '2022-01-01'
                    contactInfo:
                      name: user1
                      email: user1@gmail.com
                      phone: '1234567'
        '400':
          description: Missing Required Information
          content:
            text/plain:
              schema:
                type: string
              examples:
                example-1:
                  value: Missing Required Information
        '409':
          description: Email Already Taken
          content:
            text/plain:
              schema:
                type: string
              examples:
                example-1:
                  value: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewUser'
            examples:
              Create User user1@gmail.com:
                value:
                  email: user1@gmail.com
                  password: 123123fwefwefgvwe
                  contactInfo:
                    name: user
                    email: usermail.com
                    phone: '123456'
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
  '/users/{userId}/postings/{postingId}':
    parameters:
      - schema:
          type: string
        name: userId
        in: path
        required: true
      - schema:
          type: string
        name: postingId
        in: path
        required: true
    delete:
      tags:
        - delete
      summary: Delete posting from particular user
      operationId: delete-users-userId-postings-postingId
      responses:
        '200':
          description: posting deleted
          content:
            text/plain:
              schema:
                type: string
              examples:
                example-1:
                  value: posting deleted
        '401':
          description: Unauthorized
          content:
            text/plain:
              schema:
                type: string
              examples:
                example-1:
                  value: Unauthorized
        '404':
          description: posting not found
          content:
            text/plain:
              schema:
                type: string
              examples:
                example-1:
                  value: posting not found
      description: Delete existing posting from user
    patch:
      tags:
        - patch
      summary: Update posting from particular user
      operationId: patch-users-userId-postings-postingId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Posting'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
              examples:
                example-1:
                  value: Unauthorized
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: string
              examples:
                example-1:
                  value: posting not found
      description: Update existing posting from user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostingInfo'
  '/users/{userId}/posting':
    parameters:
      - schema:
          type: string
        name: userId
        in: path
        required: true
    get:
      tags:
        - get
      summary: Get postings from particular user
      operationId: get-users-userId-postings
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Posting'
        '401':
          description: Unauthorized
          content:
            text/plain:
              schema:
                type: string
              examples:
                example-1:
                  value: Unauthorized
      description: Get postings from particular user with userId and postingId
      parameters:
        - schema:
            type: string
          in: query
          name: postingId
    post:
      tags:
        - post
      summary: Create new posting for user
      operationId: post-users-userId-postings-postingId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Posting'
        '401':
          description: Unauthorized
          content:
            text/plain:
              schema:
                type: string
              examples:
                example-1:
                  value: Unauthorized
      description: Create new posting for user with Id
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostingInfo'
      parameters: []
  '/users/{userId}/postings/{postingId}/image':
    parameters:
      - schema:
          type: string
        name: postingId
        in: path
        required: true
      - schema:
          type: string
        name: userId
        in: path
        required: true
    post:
      tags:
        - post
      summary: Upload image for particular posting
      operationId: post-users-userId-postings-postingId-image
      responses:
        '200':
          description: New image uploaded
          content:
            application/json:
              schema:
                type: object
                properties:
                  filename:
                    type: string
              examples:
                example url:
                  value:
                    filename: testimage.jpg
        '401':
          description: Unauthorized
          content:
            text/plain:
              schema:
                type: string
              examples:
                example-1:
                  value: Unauthorized
        '404':
          description: Posting Not Found
          content:
            text/plain:
              schema:
                type: string
              examples:
                example-1:
                  value: posting not found
        '406':
          description: Maximum number of images exceed
          content:
            text/plain:
              schema:
                type: string
              examples:
                example-1:
                  value: maximum number of images uploaded for posting
      description: Upload new image for user posting with postingId
      parameters:
        - schema:
            type: string
          in: header
          name: Content-Type
          description: content type of binary data
          required: true
        - schema:
            type: string
          in: header
          name: Content-Length
          description: content length in bytes
          required: true
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: string
            examples: {}
        description: Binary stream for image data
  /postings:
    get:
      tags:
        - get
      summary: Get Posting with query params
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Posting'
              examples:
                example-1:
                  value:
                    - _id: 0
                      postingInfo:
                        title: c++ book
                        description: good boog for programmers
                        category: books
                        location: Oulu
                        price: 10
                        deliveryType: shipping
                      contactInfo:
                        name: string
                        email: string
                        phone: string
                      imageUrls:
                        - string
                      user_id: 0
      operationId: get-postings
      parameters:
        - schema:
            type: string
          in: query
          name: category
        - schema:
            type: string
          in: query
          name: location
        - schema:
            type: string
          in: query
          name: date
      description: Get postings with particular query parameters
    parameters: []
  '/images/{filename}':
    get:
      summary: Get Posting image
      tags:
        - get
      responses:
        '200':
          description: OK
          content:
            multipart/form-data:
              schema:
                type: string
              examples: {}
          headers:
            Content-Type:
              schema:
                type: string
              description: image/png
        '404':
          description: Not Found
          content:
            text/plain:
              schema:
                type: string
              examples:
                example-1:
                  value: image not found
      operationId: get-postings-postingId-images-imageId
      parameters: []
      description: Get image from particular posting
    parameters:
      - schema:
          type: string
        name: filename
        in: path
        required: true
  /login:
    post:
      tags:
        - post
      summary: Login User
      operationId: post-login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
              examples:
                example-token:
                  value:
                    accessToken: wefwegwghk213po13231.1231212r4we.21312312r41
        '401':
          description: Unauthorized
          content:
            text/plain:
              schema:
                type: string
              examples:
                example-1:
                  value: invalid username or password
      description: Login user with username and password
  /reset:
    delete:
      tags:
        - delete
      summary: ''
      operationId: delete-reset
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
              examples:
                example-1:
                  value: users and postings deleted
        '403':
          description: Forbidden
          content:
            text/plain:
              schema:
                type: string
              examples:
                example-1:
                  value: no users or postings
      description: Reset user and posting data from server
components:
  schemas:
    User:
      title: User
      type: object
      description: User model for registered users
      properties:
        _id:
          type: integer
          description: Unique identifier for the given user.
        email:
          type: string
          format: email
          example: user1@gmail.com
        createDate:
          type: string
          format: date
          description: The date that the user was created.
        contactInfo:
          $ref: '#/components/schemas/Contact'
    NewUser:
      title: NewUser
      type: object
      description: User model for registered users
      properties:
        email:
          type: string
          format: email
          example: user1@gmail.com
        password:
          type: string
        contactInfo:
          $ref: '#/components/schemas/Contact'
      required:
        - email
        - password
        - contactInfo
      x-examples: {}
    Posting:
      title: Posting
      type: object
      description: ''
      properties:
        _id:
          type: integer
        postingInfo:
          $ref: '#/components/schemas/PostingInfo'
        contactInfo:
          $ref: '#/components/schemas/Contact'
        imageUrls:
          type: array
          items:
            type: string
        user_id:
          type: integer
    PostingInfo:
      title: PostingInfo
      type: object
      description: ''
      properties:
        title:
          type: string
          example: c++ book
        description:
          type: string
          example: good boog for programmers
        category:
          type: string
          example: books
        location:
          type: string
          example: Oulu
        price:
          type: integer
          example: 10
        deliveryType:
          type: string
          enum:
            - shipping
            - pickup
          example: shipping
      required:
        - title
        - description
        - category
        - location
        - price
        - deliveryType
    Contact:
      title: ContactInfo
      type: object
      description: ''
      properties:
        name:
          type: string
        email:
          type: string
        phone:
          type: string
      x-examples:
        example-1:
          name: string
          email: string
          phone: string
  responses: {}
